---
name: dist

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install build dependencies
      run: pip install -r requirements.txt

    - name: Build packages
      run: make package

    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/

    - if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: robotpy/github-action-scp@atomic
      with:
        local: dist
        remote: public_html/2023/roborio
        host: narya.tortall.net
        username: ${{ secrets.SSH_USER }}
        privateKey: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        atomicPut: true
