---
name: dist

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - name: Install build dependencies
      run: pip install -r requirements.txt

    - name: Build packages
      run: make package

    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

    - if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      name: Publish package to WPILib artifactory
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: ${{ secrets.WPI_ARTIFACTORY_USERNAME }}
        password: ${{ secrets.WPI_ARTIFACTORY_TOKEN }}
        repository-url: https://wpilib.jfrog.io/artifactory/api/pypi/wpilib-python-release-2025-local
